import os
import json
import psycopg
from datetime import datetime

NEON_URI = "postgresql://neondb_owner:npg_wsMhrBn8UF6y@ep-restless-grass-akvdgzme-pooler.c-3.us-west-2.aws.neon.tech/neondb?sslmode=require"

def harvest_completed_pitches():
    """Fetches all completed pitches generated by Lambert3 from the Swarm Bus."""
    with psycopg.connect(NEON_URI) as conn:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT id, target_repo, pitch, created_at, processed_at
                FROM bounties
                WHERE status = 'completed' AND pitch IS NOT NULL
                ORDER BY processed_at DESC;
            """)
            rows = cur.fetchall()

    results = []
    for r in rows:
        results.append({
            "bounty_id": r[0],
            "repo": r[1],
            "pitch": r[2],
            "created_at": r[3].isoformat() if r[3] else None,
            "processed_at": r[4].isoformat() if r[4] else None
        })

    output_path = os.path.join(os.path.dirname(__file__), "harvested_pitches.json")
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

    markdown_path = os.path.join(os.path.dirname(__file__), "OUTBOUND_QUEUE.md")
    with open(markdown_path, "w", encoding="utf-8") as f:
        f.write("# Autonomous Swarm Outbound Queue\n\n")
        f.write(f"Last updated: {datetime.utcnow().isoformat()}Z\n")
        f.write(f"Total Completed Pitches from Lambert3 GPU: {len(results)}\n\n")
        f.write("| ID | Target Repo | GPU Latency Status | Pitch Preview |\n")
        f.write("| :--- | :--- | :--- | :--- |\n")
        for res in results:
            preview = res['pitch'].replace('\n', ' ')[:100] + "..." if res['pitch'] else "N/A"
            f.write(f"| #{res['bounty_id']} | `{res['repo']}` | Completed | {preview} |\n")
        
        f.write("\n## Full Pitch Payloads Ready for Dispatch\n\n")
        for res in results:
            f.write(f"### Target: `{res['repo']}` (Bounty #{res['bounty_id']})\n")
            f.write(f"**Processed by Lambert3 GPU at:** `{res['processed_at']}`\n\n")
            f.write("```text\n")
            f.write(f"{res['pitch']}\n")
            f.write("```\n\n---\n\n")

    print(f"[Dispatcher] Successfully harvested {len(results)} pitches from Swarm Bus.")
    print(f"[Dispatcher] Saved JSON to: {output_path}")
    print(f"[Dispatcher] Generated Review Queue: {markdown_path}")
    return results

if __name__ == "__main__":
    harvest_completed_pitches()
