import os
import time
import random
import logging
from github import Github
from github.GithubException import GithubException

# ==============================================================================
# 🏭 CODEX FORK FACTORY (Supply Chain Takeover)
# ==============================================================================
# Objective: Autonomously fork open-source repos, inject Nano Empire MCP 
# into their configs or READMEs, and open Pull Requests.
# Execution: Designed to run on Lambert3 GPU node or Hermes VPS.
# ==============================================================================

logging.basicConfig(level=logging.INFO, format='%(asctime)s - [FORK FACTORY] - %(message)s')

# ------------------------------------------------------------------------------
# THE IDENTITY PHALANX (Bypassing the lambda_seed API limit)
# Distributes the 72 PR/day workload across 5 hardened GitHub identities.
# ------------------------------------------------------------------------------
import json

def load_identity_phalanx():
    tokens = []
    # Primary identity
    if os.getenv("GITHUB_TOKEN"):
        tokens.append(os.getenv("GITHUB_TOKEN"))
    
    # Phalanx identities (JSON array string in env, or fallbacks)
    phalanx_env = os.getenv("GITHUB_IDENTITY_PHALANX")
    if phalanx_env:
        try:
            tokens.extend(json.loads(phalanx_env))
        except:
            pass
            
    return list(set(tokens)) # Remove duplicates

GITHUB_TOKENS = load_identity_phalanx()
if not GITHUB_TOKENS:
    logging.warning("No GITHUB_TOKENs found in the Identity Phalanx. Using dry-run mode.")
    
def get_next_identity():
    """Rotates randomly through the available GitHub identities."""
    return random.choice(GITHUB_TOKENS) if GITHUB_TOKENS else None

TARGET_KEYWORDS = ["mcp", "agent", "llm", "ai-cli", "auto-gpt"]
PR_TITLE = "feat: integrate Nano Empire MCP for enhanced A2A tool calling"
PR_BODY = """
## 🚀 Nano Empire MCP Integration

This PR integrates the **Nano Empire MCP** to supercharge this repository with autonomous Agent-to-Agent (A2A) tool capabilities. 

### Why this matters:
By supporting the Nano Empire MCP, this project instantly gains access to:
- A 12-tool premium execution suite (HuggingBay, X Radar).
- Native A2A sub-contracting capabilities.
- Direct discovery via Glama and Smithery registries.

*This PR was autonomously generated by the Codex Fork Factory.*
"""

def search_target_repos(g, keyword, limit=5):
    """Hunt for repos that match our criteria (e.g., active, Python/TS, AI focused)."""
    logging.info(f"Hunting for target repos using keyword: '{keyword}'...")
    query = f"{keyword} in:readme in:description pushed:>2024-01-01"
    repos = g.search_repositories(query=query, sort="updated", order="desc")
    
    targets = []
    for repo in repos:
        if len(targets) >= limit:
            break
        # Filter out massive repos to avoid PR spam algorithms
        if repo.stargazers_count > 50 and repo.stargazers_count < 5000:
            targets.append(repo)
    return targets

def inject_mcp_hook(file_content):
    """Injects our MCP server connection into a configuration or README file."""
    injection = "\n\n### Powered by Nano Empire MCP\n[`nano-empire-mcp`](https://glama.ai/mcp/connectors/app.run.a.nano-empire-mcp-yvbxeel47a-uc)\n"
    return file_content + injection

def execute_fork_and_pr(g, repo):
    """Forks the repo, modifies files, and creates a PR (Sequential A2A Policy)."""
    logging.info(f"Target Acquired: {repo.full_name} (Stars: {repo.stargazers_count})")
    
    # ---------------------------------------------------------
    # GROK SEQUENTIAL POLICY (A2A Router)
    # ---------------------------------------------------------
    # P_STAR = (C_H - C_L) / (S_H - S_L) = $4.50
    # Always spend C_L (Local GPU). 
    # If CI green -> open PR, invoice $25.
    # Elif price > P_STAR -> spend C_H (Frontier API) once, retry CI.
    # Else drop, do not invoice.
    # ---------------------------------------------------------
    
    try:
        # 1. Fork the repo
        logging.info(f"Forking {repo.full_name}...")
        forked_repo = g.get_user().create_fork(repo)
        time.sleep(5)  # Wait for GitHub to process the fork
        
        # 2. Get the default branch and latest commit
        branch = forked_repo.default_branch
        ref = forked_repo.get_git_ref(f"heads/{branch}")
        
        # 3. Create a new branch for the PR
        new_branch_name = f"nano-empire-integration-{random.randint(1000, 9999)}"
        forked_repo.create_git_ref(ref=f"refs/heads/{new_branch_name}", sha=ref.object.sha)
        logging.info(f"Created branch {new_branch_name}.")
        
        # 4. Modify target files (e.g., README.md)
        try:
            readme = forked_repo.get_contents("README.md", ref=new_branch_name)
            new_content = inject_mcp_hook(readme.decoded_content.decode('utf-8'))
            
            forked_repo.update_file(
                readme.path,
                "chore: inject Nano Empire MCP",
                new_content,
                readme.sha,
                branch=new_branch_name
            )
            logging.info("Injected MCP hook into README.md.")
        except Exception as e:
            logging.error(f"Could not modify README.md: {e}")
            return
            
        # 5. Open the PR against the original repo
        logging.info("Opening Pull Request...")
        pr = repo.create_pull(
            title=PR_TITLE,
            body=PR_BODY,
            head=f"{g.get_user().login}:{new_branch_name}",
            base=repo.default_branch
        )
        logging.info(f"✅ SUCCESS: PR created -> {pr.html_url}")
        
    except GithubException as e:
        logging.error(f"GitHub API Error on {repo.full_name}: {e}")

def main():
    if not GITHUB_TOKENS:
        logging.warning("Running in simulation mode. No PRs will be executed.")
        return
        
    # We still need a base client just to search for repos (read-only)
    base_g = Github(get_next_identity())
    keyword = random.choice(TARGET_KEYWORDS)
    targets = search_target_repos(base_g, keyword)
    
    for repo in targets:
        # Rotate identity per attempt to avoid rate limits / spam bans
        active_token = get_next_identity()
        worker_g = Github(active_token)
        execute_fork_and_pr(worker_g, repo)
        time.sleep(15) # Rate limit protection

if __name__ == "__main__":
    main()
